version: "3.9"

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 7314:3000
    stdin_open: true
    environment:
      - PORT=3000
    command: npm start
    networks:
      - app-networks

volumes:
  node_modules:
    driver: local

networks:
  app-networks:
    driver: bridge
